// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDVmNPb7csWsbzYVgrXMi6mMmjt4p241w',
    appId: '1:655231181668:web:c0e927e68e12ce781a1071',
    messagingSenderId: '655231181668',
    projectId: 'homework4-4f168',
    authDomain: 'homework4-4f168.firebaseapp.com',
    storageBucket: 'homework4-4f168.firebasestorage.app',
    measurementId: 'G-6DMSS40SSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAiflADd4y4VY5GaSUILdTWwdkMtkak68',
    appId: '1:655231181668:android:e1a798ff5059af861a1071',
    messagingSenderId: '655231181668',
    projectId: 'homework4-4f168',
    storageBucket: 'homework4-4f168.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzpBGulKdeU61TbCtqpxCfKKxNDVjAjsk',
    appId: '1:655231181668:ios:3ba691b766e5a11b1a1071',
    messagingSenderId: '655231181668',
    projectId: 'homework4-4f168',
    storageBucket: 'homework4-4f168.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzpBGulKdeU61TbCtqpxCfKKxNDVjAjsk',
    appId: '1:655231181668:ios:3ba691b766e5a11b1a1071',
    messagingSenderId: '655231181668',
    projectId: 'homework4-4f168',
    storageBucket: 'homework4-4f168.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDVmNPb7csWsbzYVgrXMi6mMmjt4p241w',
    appId: '1:655231181668:web:25b38f9178b7c9781a1071',
    messagingSenderId: '655231181668',
    projectId: 'homework4-4f168',
    authDomain: 'homework4-4f168.firebaseapp.com',
    storageBucket: 'homework4-4f168.firebasestorage.app',
    measurementId: 'G-577C3B9HNV',
  );
}
